### ISSUE TITLE
ui error

### ISSUE THREAD

**Issue by thomaslochet** [praveen001/go-rtmp-web-server#38]
hello, i have to error with docker

ui exited with code 1
ui       | yarn run v1.22.15
ui       | $ webpack-dev-server --host 0.0.0.0
ui       | ℹ ｢wds｣: Project is running at http://0.0.0.0:8080/
ui       | ℹ ｢wds｣: webpack output is served from /
ui       | ℹ ｢wds｣: Content not from webpack is served from /ui
ui       | ℹ ｢wds｣: 404s will fallback to /index.html
ui       | node:internal/crypto/hash:67
ui       |   this[kHandle] = new _Hash(algorithm, xofLen);
ui       |                   ^
ui       | 
ui       | Error: error:0308010C:digital envelope routines::unsupported
ui       |     at new Hash (node:internal/crypto/hash:67:19)
ui       |     at Object.createHash (node:crypto:130:10)
ui       |     at module.exports (/ui/node_modules/webpack/lib/util/createHash.js:135:53)
ui       |     at NormalModule._initBuildHash (/ui/node_modules/webpack/lib/NormalModule.js:417:16)
ui       |     at handleParseError (/ui/node_modules/webpack/lib/NormalModule.js:471:10)
ui       |     at /ui/node_modules/webpack/lib/NormalModule.js:503:5
ui       |     at /ui/node_modules/webpack/lib/NormalModule.js:358:12
ui       |     at /ui/node_modules/loader-runner/lib/LoaderRunner.js:373:3
ui       |     at iterateNormalLoaders (/ui/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
ui       |     at Array.<anonymous> (/ui/node_modules/loader-runner/lib/LoaderRunner.js:205:4) {
ui       |   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
ui       |   library: 'digital envelope routines',
ui       |   reason: 'unsupported',
ui       |   code: 'ERR_OSSL_EVP_UNSUPPORTED'
ui       | }
ui       | 
ui       | Node.js v17.2.0
ui       | error Command failed with exit code 1.
ui       | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by kinseii** [comment]
Add to ui env:
        environment:
          NODE_OPTIONS: --openssl-legacy-provider

```
    ui:
        container_name: ui
        build:
            context: .
            dockerfile: ./scripts/ui/Dockerfile
        entrypoint: yarn start
        volumes:
            - ./frontend/src/:/ui/src
        restart: unless-stopped
        expose:
            - 8080
        environment:
          NODE_OPTIONS: --openssl-legacy-provider
```
